name: ooi_acoustics
channels:
  - conda-forge
  - nodefaults
dependencies:
  - beautifulsoup4
  - echopype
  - h5netcdf
  - ipykernel
  - matplotlib
  - pip
  - python=3.12
  - s3fs
  # -- viz related --
  - datashader
  - jupyter_bokeh
  - holoviews
  - hvplot
  # -- others --
  - pip:
    - das4whales@git+https://github.com/DAS4Whales/DAS4Whales@ooi-2025
