name: ooi_acoustics_day2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - zarr
  - ipykernel
  - matplotlib
  - pip
  - h5netcdf

  # -- viz related --
  - datashader
  - jupyter_bokeh
  - holoviews
  - hvplot
  - seaborn
  # -- others --
  - pip:
    - das4whales@git+https://github.com/DAS4Whales/DAS4Whales@ooi-2025
    - -e . # Install 2025-Summer-School-Acoustics as python package in 'editable mode'
    - xrsignal
    - ooipy
